version: '3.8'
services:
   web:
       build: .
       command: python3 manage.py runserver 0.0.0.0:5000
       ports:
           - "5000:5000"
       volumes:
         - ./app:/usr/src/app
       env_file:
         - ./.env
       depends_on:
         - db
   db:
     image: postgres:12.0-alpine
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin
       - POSTGRES_DB=postgres_test
volumes:
  postgres_data: